version: '3.7'

services:
  api:
    container_name: sp_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      APP_ENV: dev
      PORT: 3000
      DB_HOST: sp_postgres
      DB_PORT: 5432
      DB_NAME: sp_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_TOKEN_SECRET: "senha_super_secreta_para_token_abcd!@a17"
      JWT_REFRESH_TOKEN_SECRET: "senha_super_refresh_token_43f@edfw"
      JWT_TOKEN_EXPIRES_IN: "1d"
      JWT_REFRESH_TOKEN_EXPIRES_IN: "1d"
      REDS_PORT: 6379
    links:
      - sp_postgres:database
      - sp_redis:redis
    command: yarn dev
    networks:
      main:
        aliases:
          - sp_api

  postgres:
    container_name: sp_postgres
    image: postgres:11.1
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sp_test
    networks:
      main:
        aliases:
          - sp_postgres

  redis:
    container_name: sp_redis
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - './.data/redis:/data'
    networks:
      main:
        aliases:
          - sp_redis
    restart: always

networks:
  main:
